---
title: "Atividades"
output: "md_document"
---

# Atividades Complementares

### Participação de Membros do Grupo em Audiências Públicas

Na tarde da quarta-feira, 22 de março de 2017 foi realizada uma audiência pública na Câmara Municipal de Curitiba para debater a revitalização do rio Belém. A iniciativa foi do vereador Goura (PDT) e teve apoio do deputado estadual Rasca Rodrigues (PV). “Nada mais apropriado que discutir a revitalização do Rio Belém no Dia Mundial da Água”, defendeu o vereador, que é vice-presidente da Comissão de Meio Ambiente da Câmara de Curitiba. Participação da Eng. Florestal Mayra Viviane Rochavetz de Lara.

[http://www.rioiguacu.pr.gov.br/2017/03/163/Audiencia-Publica-debate-os-rios- Iguacu-e-Belem-na-Camara-de-Curitiba.html](http://www.rioiguacu.pr.gov.br/2017/03/163/Audiencia-Publica-debate-os-rios-
Iguacu-e-Belem-na-Camara-de-Curitiba.html)

### Participação de Membros do Grupo em Eventos de Extensão

* Evento de Extensão “Um Olhar para os Rios Urbanos” do Projeto “Engenharia – Água & Ação” dia 26 de maio de 2017 com aula teórica e aula de campo:
   + Palestra: Programa de Revitalização de Rios Urbanos (PRRU); 
      - Jefferson Skroch/USHI/Sanepar e Rosélis Presznhuk/USEA/Sanepar
   + Visita ao Córrego do Aviário Municipal: Percebendo a bacia de drenagem,        morfologia do rio e existência de saneamento básico do local. Medição de       OD nos pontos visitados e interpretação de seu valor;
   + [https://docs.ufpr.br/~rtkishi.dhs/extensao/2017_riosurbanos/](https://doc s.ufpr.br/~rtkishi.dhs/extensao/2017_riosurbanos/)
* Evento de Extensão “Revitalização da Praça Renato Zorze” junto ao Colégio de Ensino Municipal João Macedo Filho em 11 de novembro de 2017:
   + A atividade consistiu em participar junto com outros projetos, a convite     do Projeto “Engenharia Água e Ação” e da direção do Colégio de Ensino         Municipal João Macedo Filho, do programa de revitalização da praça. A         atividade contou com a participação de cerca de cinquenta alunos e suas       famílias e de ONGs. A participação do Projeto “Areião das Águas” foi o de     colaborar com o plantio de cerca de 50 mudas para recomposição da mata        ciliar do córrego Areiãozinho, vizinho à praça e ao colégio.

### participação de Membros do Grupo em Reunião do Grupo de Trabalho em Educação Ambiental do Ministério Público

Na terça-feira dia 28 de novembro a Servidora TA lotada no Biofix participou em nome do Projeto Areião das Águas da Reunião Mensal do Grupo de Trabalho em Educação Ambientla (GTEA) do Centro de Apoio Operacional das Promotorias de Proteção ao Meio Ambiente e de Habitação e Urbanismo.

O Projeto passará a integrar o grupo com a proposição de ser um exemplo de educação ambiental em torno de um rio urbano.

# Atividades de Campo

1. Visita a todos os trechos do rio Areiãozinho com o Grupo de Saúde Coletiva da UFPR – Litoral. Prof. Paulo Bracarense, Prof. Neilor Kleinubing, Tatiana Kleinubing e Natali Calderari em 25 de março de 2017;
2. Visita ao trecho 2 do rio Arieiãzinho para preparação de pesquisa sobre fixação de carbono para o programa de especialização do Biofix. Prof. Paulo Bracarense e Maria Emilia Martins Ferreira em 07 de maio de 2017;
3. Realização de inventário florestal da primeira fase do Trecho 2 do rio Areiãzinho em três atividades de campo realizadas nos dias 30 de junho, 17 de julho e 05 de outubro de 2017. Participaram dessa atividade o prof. Bracarense, a técnica do Biofix Maria Emilia acompanhada de sua equipe (Vicente, Deivison, Myrcia, e William) e os acadêmicos do projeto (Helena, Aline, Victória e Gabriel).

# Participação em Programas de Educação

1. Especialização no Curso de Elaboração e Gestão de Projetos em Recursos Hídricos Municipais: Instituto Federal de Educação do Ceará (IFCE) e Agência Nacional das Águas (ANA). Título do Projeto: “Programa de Educação Ambiental com Intervenção no Rio Areiãozinho”. Paulo Afonso Bracarense Costa.
    + Cursos ANA (Agência Nacional de Águas) realizados no primeiro semestre de 2017:
        - Ambiente virtual de aprendizagem - 20/03 a 16/04 – 40h;
        - Princípios de hidrologia ambiental – 20/03 a 16/04 – 20h;
        - Noções de irrigação e drenagem agrícola – 17/04 a 23/04 – 10h;
        - Manejo e conservação de água e solos – 24/04 a 07/05 – 20h;
        - Drenagem urbana – 15/04 a 21/05. 10h;
        - Sistema de abastecimento de água – 22/05 a 18/06 – 40h;
        - Tratamento de águas residuárias – 12/06 a 09/07 – 40h;
        - Reuso de águas – 10/07 a 23/07 – 10h;
        - Resíduos sólidos, gestão e gerenciamento – 17/07 a 30/07 – 10h.
    + Cursos ANA (Agência Nacional de Águas) realizados no segundo semestre de       2017:
        - Princípios e conceitos em gestão de recursos hídricos – 04/09 a               17/09 - 20h;
        - Aspectos legais e institucionais de gestão de rec. hídricos – 18/09           a 01/10 – 20h;
        - Instrumento de gestão de recursos hídricos – 02/10 a 15/10 – 20h;
        - Educação e saúde para a gestão de recursos hídricos – 16/10 a 22/10           – 10h;
        - Planejamento, medição e avaliação da gestão local – 23/10 a 29/10 -           10h;
        - Planejamento urbano e gestão ambiental e municipal – 30/10 a 26/11 -           40h;
        - Licenciamento ambiental e obras de saneamento – 27/11 a 03/12 - 10h.
2. MBA em Gestão Ambiental do PECCA (Programa de Educação Continuada em Ciências Agrárias). Título do Projeto: “Análise do potencial de fixação de carbono na recomposição da mata ciliar do rio Areiãzinho“. Maria Emília Martins Ferreira. Orientador: Prof. Dr. Carlos Roberto Sanquetta.      
3. MBA em Gestão Ambiental do PECCA (Programa de Educação Continuada em Ciências Agrárias). Título do Projeto: “Ações sustentáveis no ambiente escolar e seu reflexo na sociedade“. Camila Aguiar Campolina de Carvalho. Orientador: Prof. Dr. Paulo Afonso Bracarense Costa.      

# Participação em Seminários, Visitas e Ações de Divulgação do Projeto

### Visita ao Centro de Tratamento de Águas Residuárias La Farfana (Chile)

Visita à Planta de Tratamiento de Aguas Servidas La Farfana em Santiago do Chile no dia 27 de Julho de 2017. Paulo Bracarense, Maria Emilia Martins Ferreira e Helena Bracarense.

### Seminário Presencial IFCE/ANA – Florianópolis (SC)

Participação do Seminário Presencial do Curso EAD em Gestão de Recursos Hídricos Municipais do Instituto Federal de Educação Científica e Tecnológica do Ceará e Aguência Nacional de Águas (ANA).

Apresentação do Mapa Estratégico do Projeto “Areião das Águas”. Florianópolis em 3,4 e 5 de agosto de 2017.   
   
### 1° Encontro de Creditação da Extensão – UFPR  

Participação no Encontro de Creditação da PROEC no Auditório Mauricio Bissolim no Campus Botânico, Setor de Ciências da Saúde.

### Ciclo Maui de Palestras – Mestrado em Meio Ambiente Urbano e Industrial 13, 14 e 15 de Setembro de 2017.

* Apresentação de Poster:
   + Título: Revitalização de rio Urbano: Projeto “Areião das Águas”;
   + Álvaro Mathias, Paulo Bracarense,  Reinaldo Fontes Cavalcante.                 Departamento de Eng. Química (UFPR); Departamento de Estatística (UFPR);       Curso de Engenharia Ambiental e Sanitária (IFCE).

### Participação no SIEPE – 3 e 4 de outubro de 2017

Apresentação do Projeto Areião das Águas no 16o ENEC pelos alunos Aline Guidolin, Alisson Esser, Gabriel Melo, Helana Bracarense, Luana Flores e Victória Torres.
   
### Gravação do Programa “Universidade Além dos Muros” da Apufpr

Gravação do programa em 26 de outubro de 217. Programa colocado no ar em
03 de novembro de 2017.

Link para o vídeo [aqui](http://apufpr.org.br/projeto-de-preservacao-do-rio-areiaozinho-integra-comunidade-academica-e-moradores-2/).

### Participação no 35° SEURS

Apresentação do Projeto “Areião da Águas” no 35o Seminário de Extensão Universitária da Região Sul. UNILA e UNIOESTE em Foz do Iguaçu – 30, 31 de outubro e 1° de novembro.

Firmado acordos de intensão de cooperação com os Programas Avifauna – Argentina (Prof. Diego Centurion), Projeto de Extensão “Águas 2017” de Educação Ambiental UFRGS - (Profa. Teresinha Guerra) e Planejamento Urbano UEL (Prof. Gilson Jacob Bergoc).

### Seminário Presencial IFCE/ANA – Florianópolis (SC)

Participação do Seminário Presencial do Curso EAD em Gestão de Recursos Hídricos Municipais do Instituto Federal de Educação Científica e Tecnológica do Ceará e Aguência Nacional de Águas (ANA).

Apresentação das Atividades de Agosto a Dezembro do Projeto “Areião das Águas”. Florianópolis em 14, 15 e 16 de dezembro de 2017.

# Eventos de Extensão Relacionados ao Projeto "Areião das Águas"

### Ciclo de Debates em Educação Ambiental

Os seminários constituem-se em programa adicional ao projeto para a preparação dos alunos bolsistas e voluntários do projeto Areião das Águas. Participam regularmente dos seminários os bolsistas Victória, Gabriel e Jardel (em caráter obrigatório) e os voluntários acadêmicos Helena, Luana, Alisson, Bruno e Aline.

Na primeira fase os seminários consistirão na apresentação dos capítulos do livro “Introdução à Engenharia Ambiental e o Desafio do Desenvolvimento Sustentável” de Benedito Braga.   

Pré-seminário: leitura crítica dos capítulos introdutórios. Cap. 1. A Crise Ambiental, Cap. 2. Leis da Conservação da Massa e da Energia e Cap. 3. Ecossisitemas.

* Seminário 1 – Cap. 4 – Ciclos Biogeoquímicos – Álvaro Matias em 01/09;
* Seminário 2 – Cap. 5 – A Dinâmica das Populações – Paulo Bracarense em 19/10;
* Seminário 3 – Cap. 6 – Bases do Desenvolvimento Sustentável – Gabriel Melo em 09/11;

Os seminários retornarão em março de 2018 na seguinte ordem:

* Seminário 4 – Cap. 7 – A Energia e o Meio Ambiente – Helena;
* Seminário 5 – Cap. 8 – O Meio Aquático – Aline;
* Seminário 6 – Cap. 9 – O Meio Terrestre – Victória;
* Seminário 7 – Cap. 10 – O Meio Atmosférico – Luana;
* Seminário 8 – Cap. 11 – Conceitos Básicos de Desenvolvimento Sustentável – Jardel;
* Seminário 9 – Cap. 12 – Economia e Meio Ambiente – Jayme;
* Seminário 10 – Cap. 13 – Aspectos Legais e Institucionais – Bruno;
* Seminário 11 – Cap. 14 – Avaliação de Impactos Ambientais – Alisson;
* Seminário 12 – Cap. 15 – Gestão Ambiental – Amanda;

# Comunicação Institucional

* Endereço Postal:
    + Centro Politécnico – Jardim das Américas – Ed. do Setor de Ciências           Exatas – Bloco PA – 2° andar, sala 213, Caixa Postal 19.081 – CEP 81.531       – 990 – Curitiba (PR).
* Referência no Site do Setor de Ciências Exatas:
    + [http://www.exatas.ufpr.br/portal/blog/tag/areiao-das-aguas/](http://www.exatas.ufpr.br/portal/blog/tag/areiao-das-aguas/)
* Endereço no facebook “Projeto Areião das Águas”:
    + [https://www.facebook.com/areiaodasaguas/](https://www.facebook.com/areiaodasaguas/)
* Endereço na WEB:
    + [http://areiaodasaguas.blogspot.com.br/](http://areiaodasaguas.blogspot.com.br/)
* Rede WhatsApp
    + Criado por +55 41 9184-8567 em 23/12/2016.
   
  
   
   