---
title: "Projeto de Intervenção"
output: "md_document"
   
---

**Problema:**

A partir do conteúdo apresentado, detalhar como a problemática apresentada no projeto de intervenção será solucionada, tendo em vista a viabilidade de resolução. Tomar como base os seguintes aspectos: (i) ações de intervenção; (ii) atores envolvidos e (iii) viabilidade técnica e econômica/financeira.

**Documento original escrito por:**Paulo Afonso Bracarense Costa

# 1 Educação Socioambiental

## 1.1 Ações de Intervenção

Construir um projeto educacional que una o saber acadêmico e o saber popular produzindo material didático para crianças e jovens estudantes (8 escolas na bacia) e material de divulgação e formação para adultos (comunidade, setor produtivo, moradores, igrejas e outros elementos que convivem na bacia). 

Objetiva-se que este projeto seja inclusivo e participativo. Serão tomadas como paradigmas as teorias construtivistas de Jean Piaget (Epistemologia Genética) e de Lev Vygotsky (Teoria do Desenvolvimento Cultural) que propugnam que o conhecimento é construído durante toda a vida do indivíduo.  Nesse contexto, deseja-se colocar a academia (representada no projeto por professores, alunos e servidores) como elemento intermediário entre o saber erudito e o popular capaz de incorporar, em média, as experiências e concepções de toda uma comunidade. Se esse enfoque se mostrar possível, consubstancia-se então, a concepção construtivista apresentada por Bruna Sola (2016): “o fator humano no meio social (ou socioambiental) tem uma importância destacada, e o indivíduo é considerado alguém que vai se construindo em meio à rede de relações que estabelece”.

Em termos materiais espera-se produzir material de apoio (didático e de divulgação) para junto com as escolas e a comunidade serem utilizados para o trabalho de educação ambiental. Outras mídias poderão eventualmente serem utilizadas nesse processo.

## 1.2 Atores Envolvidos

## 1.3 Viabilidade Técnica

# 2 Caracterização da Bacia

## 2.1 Ações de Intervenção

Um resultado importante a ser alcançado é a caracterização física completa da bacia do rio Ariãozinho quanto ao seu desague, curso d’água, padrão de drenagem, área, perímetro e comprimento, declividade, altitude média, tempo de concentração, coeficiente de compacidade, fator de forma, ordenamento dos cursos de água, densidade de drenagem, densidade de confluência, rugosidade, extensão média de escoamento superficial.

Essas classificações permitirão analisar o comportamento da bacia e servem como indicadores de seu comportamento.

## 2.2 Atores Envolvidos

## 2.3 Viabilidade Técnica

# 3 Controle da Qualidade da Água

## 3.1 Açoes de Intervenção

Hidrometria é o termo para a medição de grandezas relativas ao estuda da água. Pretende-se fazer um estudo aprofundado na área em toda bacia do rio Areiãzinho estabelecendo-se os padrões atuais e os desejados através dos indicadores clássicos da hidrometria tais como vazão, nível da água, índices pluviométricos e também parâmetros de avaliação da qualidade como IQA (índice da qualidade da água), oxigênio dissolvido, coliformes fecais, pH, DBO (Demanda bioquímica de oxigênio, nitrato, fosfato total, temperatura da água, turbidez e sólidos totais.

## 3.2 Atores Envolvidos

## 3.3 Viabilidade Técnica

# 4 Destinação do Resíduo Sólido

## 4.1 Ações de Intervenção

Entre os maiores problemas ambientais que ocorrem no ambiente urbano, referentes aos recursos hídricos estão o descaso com a ocorrência de erosão, os despejos de esgoto e efluentes industriais, a invasão dos leitos por ocupação subnormal e o lançamento de lixo e entulho nos corpos d’água e em seus arredores. Além da impermeabilização dos solos, a ocupação das margens dos rios, trouxe o problema de inundações e dos resíduos veiculados por elas, assim há lixo de todas espécies nos corpos d’água e a necessidade de desassoreamento é frequente. Espera-se que a realização de estudos específicos e ações educativas sobre a destinação de resíduos sólidos na bacia do rio Areiãzinho possam melhorar a qualidade ambiental e de vida da população de sua bacia.

## 4.2 Atores Envolvidos

## 4.3 Viabilidade Técnica

# 5 Inventário Florestal da Mata Ciliar

## 5.1 Ações de Intervenção

Matas ciliares são formações vegetais que ocorrem às margens dos cursos d’água, como rios e lagos, também são encontradas protegendo as nascentes e cabeceiras. Um dos objetivos deste trabalho será aplicar uma metodologia-padrão para a continuidade de estudos de composição florística e dinâmica florestal da mata ciliar do rio Areiãozinho ao mesmo tempo em que pretende fazer uma avaliação da capacidade de fixação de carbono com a recomposição de sua mata ciliar.

## 5.2 Atores Envolvidos

## 5.3 Viabilidade Técnica

# 6 Urbanização e hortas comunitárias

## 6.1 Ações de Intervenção

Algumas áreas da bacia do rio Areiãzinho, em particular áreas públicas em sua margem, podem receber um tratamento urbanístico e eventualmente receberem programas de organização de hortas comunitárias. Em ambos os casos já há algumas iniciativas da população de recuperação de áreas para jardinagem e para o cultivo de hortas comunitárias. Esses resultados só poderão ser alcançados com a participação popular, a orientação acadêmica e através de acordos com os órgãos municipais responsáveis pelas áreas como a Secretaria Municipal de Meio Ambiente, Secretaria Municipal de Urbanismo e Secretária Municipal de Abastecimento. Em todos os casos já forma realizadas reuniões para o estudo específico do rio Areiãozinho.

## 6.2 Atores Envolvidos

## 6.3 Viabilidade Técnica

# 7 Fossas sépticas com tecnologia alternativa

## 7.1 Ações de Intervenção

A fossa séptica biodigestora é um sistema de tratamento de esgoto, no qual ocorre decomposição anaeróbia das fezes por bactérias metanogênicas, resultando em biogás e efluente estabilizado. O efluente pode ser utilizado como biofertilizante. Essa tecnologia em geral é empregada onde não há coleta de esgoto ou unidades de tratamento convencionais. Muitas vezes os dejetos são jogados diretamente no rio, contaminando a água. O objetivo do estudo será verificar a viabilidade econômica e operacional da instalação desse tipo de fossa para locais na bacia com dificuldade de ligação à rede de esgoto da cidade.

## 7.2 Atores Envolvidos

## 7.3 Viabilidade Técnica

# 8 Saúde coletiva

## 8.1 Ações de Intervenção

A Organização Mundial de Saúde (OMS) menciona o saneamento básico precário como uma grave ameaça à saúde humana. Apesar de disseminada no mundo, a falta de saneamento básico ainda é muito associada à pobreza afetando principalmente a população de baixa renda; mais vulnerável devido à subnutrição e muitas vezes pela higiene inadequada. Doenças relacionadas a sistemas de água e esgoto inadequados e as deficiências com a higiene causam a morte de milhões de pessoas todos os anos, com prevalência em regiões de baixa renda.

Um dos objetivos do projeto é fazer um diagnóstico sobre como o saneamento inadequado afeta a saúde das populações dos bairros da bacia do rio Areiãzinho. Um olhar mais detalhado será dirigido ao mosquito *Aedes aegypti* que é o mosquito transmissor da dengue e da febre amarela urbana.

## 8.2 Atores Envolvidos

## 8.3 Viabilidade Técnica

# 9 Observação avifaunística

## 9.1 Ações de Intervenção

Um dos métodos de educação ambiental em construção no projeto é o chamado “birdwatching”, ou observação de pássaros, que é um hobby antigo, que começou na Inglaterra do século XVIII.

Esse processo de observação aguça a percepção das pessoas com relação às atividades da natureza, as pessoas passam a enxergar mais, ouvir mais e, para algumas pessoas, passam até a reconhecer as vozes das aves: a pessoa ouve o canto ou um pequeno chamado, e já sabe qual é a ave.

## 9.2 Atores Envolvidos

## 9.3 Viabilidade Técnica

# 10 Construções sustentáveis

## 10.1 Ações de Intervenção

Segundo o Manual de Escolas Sustentáveis do MEC^<a href="#bk">1</a>^  “escolas sustentáveis são definidas como aquelas que mantêm relação equilibrada com o meio ambiente e compensam seus impactos com o desenvolvimento de tecnologias apropriadas, de modo a garantir qualidade de vida às presentes e futuras gerações. Esses espaços têm a intencionalidade de educar pelo exemplo e irradiar sua influência para as comunidades nas quais se situam. A transição para a sustentabilidade nas escolas é promovida a partir de três dimensões inter-relacionadas: espaço físico, gestão e currículo”.

Com relação ao espaço físico, o manual propõe a utilização de materiais construtivos mais adaptados às condições locais e de um desenho arquitetônico que permita a criação de edificações dotadas de conforto térmico e acústico, que garantam acessibilidade, gestão eficiente da água e da energia, saneamento e destinação adequada de resíduos. Esses locais possuem áreas propícias à convivência da comunidade escolar, estimulam a segurança alimentar e nutricional, favorecem a mobilidade sustentável e respeitam o patrimônio cultural e os ecossistemas locais.

O projeto propõe desenvolver metodologia de reforma construtiva através de diagnósticos de “déficit de sustentabilidade” realizados através de pesquisas participativas com professores, pais e alunos.

## 10.2 Atores Envolvidos

## 10.3 Viabilidade Técnica

# 11 Renaturalização do rio

# 11.1 Ações de Intervenção

Até recentemente os rios urbanos foram considerados como meros canais desconsiderando-se os aspectos físicos e ambientais envolvidos. Segundo Zahed Filho (2009) durante muito tempo, os projetos de engenharia visavam retificar o leito dos rios e córregos, de forma a aumentar a velocidade de escoamento e direcionar a vazão para jusante, a fim de se obter novas terras para a urbanização e diminuir os efeitos locais de cheias. Assim, com a realização de obras hidráulicas, o perfil do rio é diminuído e o seu leito aprofundado. O aumento da capacidade de vazão reduz a frequência de transbordamento das cheias médias, porém permanecem as grandes cheias. 

A conscientização sobre os danos causados à natureza, frutos das interações entre as atividades antrópicas e o meio ambiente permite que sejam consideradas novas estratégias dirigidas à renaturalização de rios e córregos, ou seja, o retorno das condições iniciais/naturais dos cursos hídricos. 

## 11.2 Atores Envolvidos

## 11.3 Viabilidade Técnica

Por ser um rio urbano, a tarefa de recuperação do rio Areiãzinho torna-se um pouco mais complicada. O rio possui inúmeros trechos retificados com leito e margens protegidas, havendo um maior comprometimento das relações biológicas. 

Segundo o Projeto PLANÁGUA SEMADS/GTZ de Cooperação Brasil – Alemanha, a renaturalização tem como objetivos: (i) a recuperação de córregos e rios de modo a regenerar o mais próximo possível a biota natural, atrvés de manejo regular ou de programdas de renaturalização, (ii) preservar as áreas naturais de inundação e impedir qualquer usos que inviabilizem tal função e (iii) demonstrar as possibilidades de preservar, conservar e renaturalizar o leito dos rios as zonas marginais e as baixadas inundáveis.

<blockquote id="bk"> O Manual de Escolas Sustentáveis corresponde à Resolução nº 18 de 21 de maio de 2013 que destina recursos financeiros a escolas públicas municipais, estaduais e distritais que possuam alunos matriculados na educação básica a fim de favorecer a melhoria da qualidade de ensino e a promoção da sustentabilidade socioambiental nas unidades escolares. MEC (2013).</blockquote>

# Referências Bibliográficas

<cite id="castorina">Castorina, J.A., Lerner, E.F.D. e Oliveira, M.K. de (1996). Piaget, Vygotsky. Novas Contribuições para o Debate. Editora Ática. São Paulo (SP).</a></cite>
<br/>
<br/>
<cite id="lataille">De La Taille, Y., Oliveira, M.K. e Dantas, H. (1992). Piaget, Vygotsky, Wallon. Teorias Psicogenéticas em Discussão. Summus Editorial. São Paulo (SP).</cite>
<br/>
<br/>
<cite id="macedo">Macedo, R. M. S. (1978). Piaget, Vida e Obra. Coleção Os Pensadores. Ed. Abril Cultural. Rio de Janeiro (RJ).</cite>
<br/>
<br/>
<cite id="marques">Marques, L. (2009). Capitalismo e Colapso Ambiental. Ed. Unicamp. Campinas (SP).</cite>
<br/>
<br/>
<cite id="philipijr">Philippi Jr., A. e Pelicioni, M.C.F. (2005). Educação Ambiental e Sustentabilidade. USP. Ed. Manole. São Paulo (SP).</cite>
<br/>
<br/>
<cite id="piaget">Piaget, J. (1978). A Epistemologia Genética. Coleção os Pensadores. Ed. Abril Cultural. Rio de Janeiro (RJ).</cite>
<br/>
<br/>
<cite id="sola">Sola, B. (2015). A Dinâmica do Aprender e do Ensinar na Educação à Distância. Biblioteca do NEAD/UFJF. Juiz de Fora (MG). Disponível em <a href="http://www.cead.ufjf.br/wp-content/uploads/2015/05/media_biblioteca_dinamica_aprender.pdf"/>http://www.cead.ufjf.br/wp-content/uploads/2015/05/media_biblioteca_dinamica_aprender.pdf. Última visita em 5 de fevereiro de 2018.</cite>
<br/>
<br/>
<cite id="zahed">Zahed Filho, K., J. R. S. Martins, M. f. do Amaral Porto e R. L. L. Porto (2009). Renaturalização de rios em ambientes urbanos. In: Águas em ambientes urbano. PHC 2537. Departamento de Engenharia Hidráulica e Sanitária. Escola Politécnica da Universidade de São Paulo (USP). São Paulo (SP).</cite>

